### ISSUE TITLE
As a Developer i want to see a definition of the Pickle and Rope in the Style Guide.

### ISSUE THREAD

**Issue by Tezza48** [Tezza48/HerdingCatsOnRollerskates#38]

**Comment by bsmith93** [comment]
![laser-01](https://user-images.githubusercontent.com/6282428/38281463-a13538be-37a2-11e8-98fa-a1aee0a9cfd3.gif) skinned rope as a laser pointer.
This will probably need the additional functionality:
- a circular point at the end where the mouse is.
- to hide and appear based on which cat you're interacting with.
